version: '3.8'

services:
  postgres:
    image: postgres:latest
    container_name: postgres_container
    environment:
      POSTGRES_USER: "admin"
      POSTGRES_PASSWORD: "0000"
      POSTGRES_DB: shopsmartdb
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data
      - ./db_init:/docker-entrypoint-initdb.d

  spark:
    build: .
    container_name: spark_container
    environment:
      SPARK_MODE: master
      SPARK_LOCAL_DIR: /tmp
    ports:
      - "8081:8080"
    volumes:
      - ./etl:/etl
    command: ["/opt/bitnami/spark/bin/spark-submit", "--jars", "/opt/bitnami/spark/jars/postgresql-42.7.3.jar", "/etl/etl_script.py"]

volumes:
  db_data:
